/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestordebanca;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.security.SecureRandom;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showConfirmDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author santi
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla
     */
    Conexion cone = new Conexion();
    String usuario;
    SecureRandom random = new SecureRandom();
    public Pantalla() {
        initComponents();
        cone.estableceConnection();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jDialog3 = new javax.swing.JDialog();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jDialog4 = new javax.swing.JDialog();
        jPasswordField2 = new javax.swing.JPasswordField();
        jTextField3 = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jDialog5 = new javax.swing.JDialog();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jDialog6 = new javax.swing.JDialog();
        jFormattedTextField6 = new javax.swing.JFormattedTextField();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jDialog7 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jDialog1.setMaximumSize(new java.awt.Dimension(800, 550));
        jDialog1.setMinimumSize(new java.awt.Dimension(800, 550));
        jDialog1.setPreferredSize(new java.awt.Dimension(800, 550));
        jDialog1.setResizable(false);
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setBackground(new java.awt.Color(51, 153, 0));
        jButton3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 0));
        jButton3.setText("Consultar Saldo");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jButton4.setBackground(new java.awt.Color(51, 153, 0));
        jButton4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 0));
        jButton4.setText("Ingresar Dinero");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jButton5.setBackground(new java.awt.Color(51, 153, 0));
        jButton5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 51, 0));
        jButton5.setText("Retirar Dinero");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        jButton6.setBackground(new java.awt.Color(51, 153, 0));
        jButton6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 51, 0));
        jButton6.setText("Transferir");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, -1));

        jButton7.setBackground(new java.awt.Color(51, 153, 0));
        jButton7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 51, 0));
        jButton7.setText("Movimientos");
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 210, -1, -1));

        jButton8.setBackground(new java.awt.Color(51, 153, 0));
        jButton8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 51, 0));
        jButton8.setText("Salir");
        jButton8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 0));
        jLabel6.setText("CLIENTE");
        jDialog1.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, 70));

        jLabel11.setBackground(new java.awt.Color(0, 102, 102));
        jLabel11.setOpaque(true);
        jDialog1.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 900, 100));

        jLabel10.setBackground(new java.awt.Color(0, 153, 153));
        jLabel10.setOpaque(true);
        jDialog1.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 900, 210));

        jLabel9.setBackground(new java.awt.Color(0, 204, 204));
        jLabel9.setOpaque(true);
        jDialog1.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 900, 330));

        jLabel8.setBackground(new java.awt.Color(51, 255, 255));
        jLabel8.setOpaque(true);
        jDialog1.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        jDialog2.setMinimumSize(new java.awt.Dimension(800, 550));
        jDialog2.setResizable(false);
        jDialog2.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setBackground(new java.awt.Color(51, 153, 0));
        jButton9.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 51, 0));
        jButton9.setText("Dar de Baja");
        jButton9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        jButton10.setBackground(new java.awt.Color(51, 153, 0));
        jButton10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 51, 0));
        jButton10.setText("Salir");
        jButton10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, -1, -1));

        jButton11.setBackground(new java.awt.Color(51, 153, 0));
        jButton11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 51, 0));
        jButton11.setText("Dar de Alta");
        jButton11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jButton12.setBackground(new java.awt.Color(51, 153, 0));
        jButton12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 51, 0));
        jButton12.setText("Modificar Cliente");
        jButton12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        jButton13.setBackground(new java.awt.Color(51, 153, 0));
        jButton13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jButton13.setForeground(new java.awt.Color(0, 51, 0));
        jButton13.setText("Consultar Cliente");
        jButton13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jDialog2.getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 102, 102));
        jLabel12.setOpaque(true);
        jDialog2.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 800, 200));

        jLabel13.setBackground(new java.awt.Color(0, 153, 153));
        jLabel13.setOpaque(true);
        jDialog2.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 800, 210));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 0));
        jLabel14.setText("ADMINISTRADOR");
        jDialog2.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, 70));

        jLabel15.setBackground(new java.awt.Color(0, 204, 204));
        jLabel15.setOpaque(true);
        jDialog2.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 800, 330));

        jLabel16.setBackground(new java.awt.Color(51, 255, 255));
        jLabel16.setOpaque(true);
        jDialog2.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        jDialog3.setMinimumSize(new java.awt.Dimension(290, 400));
        jDialog3.setResizable(false);
        jDialog3.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPasswordField1.setBackground(new java.awt.Color(153, 255, 255));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 160, -1));

        jTextField2.setBackground(new java.awt.Color(153, 255, 255));
        jDialog3.getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 160, -1));

        jButton16.setBackground(new java.awt.Color(51, 153, 0));
        jButton16.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jButton16.setForeground(new java.awt.Color(0, 51, 0));
        jButton16.setText("Iniciar Sesión");
        jButton16.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jDialog3.getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 140, -1));

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 102, 0));
        jLabel22.setText("Contraseña");
        jDialog3.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 102, 0));
        jLabel21.setText("DNI");
        jDialog3.getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel20.setBackground(new java.awt.Color(0, 102, 102));
        jLabel20.setOpaque(true);
        jDialog3.getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 750, 110));

        jLabel19.setBackground(new java.awt.Color(0, 153, 153));
        jLabel19.setOpaque(true);
        jDialog3.getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 750, 260));

        jLabel18.setBackground(new java.awt.Color(0, 204, 204));
        jLabel18.setOpaque(true);
        jDialog3.getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 750, 370));

        jLabel17.setBackground(new java.awt.Color(51, 255, 255));
        jLabel17.setOpaque(true);
        jDialog3.getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 420));

        jDialog4.setLocation(new java.awt.Point(0, 0));
        jDialog4.setMinimumSize(new java.awt.Dimension(290, 400));
        jDialog4.setResizable(false);
        jDialog4.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPasswordField2.setBackground(new java.awt.Color(153, 255, 255));
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jDialog4.getContentPane().add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 160, -1));

        jTextField3.setBackground(new java.awt.Color(153, 255, 255));
        jDialog4.getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 160, -1));

        jButton17.setBackground(new java.awt.Color(51, 153, 0));
        jButton17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jButton17.setForeground(new java.awt.Color(0, 51, 0));
        jButton17.setText("Iniciar Sesión");
        jButton17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jDialog4.getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 140, -1));

        jLabel23.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 102, 0));
        jLabel23.setText("Contraseña");
        jDialog4.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 0));
        jLabel24.setText("DNI");
        jDialog4.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel25.setBackground(new java.awt.Color(0, 102, 102));
        jLabel25.setOpaque(true);
        jDialog4.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 750, 110));

        jLabel26.setBackground(new java.awt.Color(0, 153, 153));
        jLabel26.setOpaque(true);
        jDialog4.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 750, 260));

        jLabel27.setBackground(new java.awt.Color(0, 204, 204));
        jLabel27.setOpaque(true);
        jDialog4.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 750, 370));

        jLabel28.setBackground(new java.awt.Color(51, 255, 255));
        jLabel28.setOpaque(true);
        jDialog4.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 420));

        jDialog5.setMaximumSize(new java.awt.Dimension(900, 580));
        jDialog5.setMinimumSize(new java.awt.Dimension(900, 580));
        jDialog5.setResizable(false);
        jDialog5.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jDialog5.getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 150, 40));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jDialog5.getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 320, 40));

        jTextField10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jDialog5.getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 520, 40));

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jDialog5.getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 150, 40));

        jButton21.setBackground(new java.awt.Color(51, 153, 0));
        jButton21.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton21.setForeground(new java.awt.Color(0, 51, 0));
        jButton21.setText("Guardar Cambios");
        jButton21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jDialog5.getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, 170, -1));

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        jFormattedTextField1.setText("(AAAA-MM-DD)");
        jFormattedTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18));
        jFormattedTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFormattedTextField1MouseClicked(evt);
            }
        });
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        jDialog5.getContentPane().add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 160, 40));

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#########"))));
        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });
        jDialog5.getContentPane().add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 130, 40));
        jFormattedTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18));

        jButton14.setBackground(new java.awt.Color(51, 153, 0));
        jButton14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton14.setForeground(new java.awt.Color(0, 51, 0));
        jButton14.setText("Guardar");
        jButton14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jDialog5.getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 480, -1, -1));

        jButton15.setBackground(new java.awt.Color(51, 153, 0));
        jButton15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jButton15.setForeground(new java.awt.Color(0, 51, 0));
        jButton15.setText("Generar IBAN y PASS");
        jButton15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jDialog5.getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 190, 30));

        try {
            jFormattedTextField5.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########?")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField5ActionPerformed(evt);
            }
        });
        jFormattedTextField5.setFont(new java.awt.Font("Segoe UI", 0, 18));
        jDialog5.getContentPane().add(jFormattedTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 120, 130, 40));
        jFormattedTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jDialog5.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 130, 40));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jDialog5.getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 300, 40));

        jLabel42.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 102, 0));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("Formulario Cliente");
        jDialog5.getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 730, 40));

        jLabel40.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 102, 0));
        jLabel40.setText("Teléfono");
        jDialog5.getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel41.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 102, 0));
        jLabel41.setText("IBAN");
        jDialog5.getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jLabel39.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 102, 0));
        jLabel39.setText("Contraseña");
        jDialog5.getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, -1, -1));

        jLabel36.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 102, 0));
        jLabel36.setText("DNI");
        jDialog5.getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, -1, -1));

        jLabel35.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 102, 0));
        jLabel35.setText("Apellidos");
        jDialog5.getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        jLabel38.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 102, 0));
        jLabel38.setText("Dirección");
        jDialog5.getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        jLabel37.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 102, 0));
        jLabel37.setText("Fecha Nacimiento");
        jDialog5.getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, -1));

        jLabel34.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 102, 0));
        jLabel34.setText("Nombre");
        jDialog5.getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel33.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 102, 0));
        jLabel33.setText("Ciudad");
        jDialog5.getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, -1, -1));

        jLabel29.setBackground(new java.awt.Color(0, 102, 102));
        jLabel29.setOpaque(true);
        jDialog5.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 900, 120));

        jLabel30.setBackground(new java.awt.Color(0, 153, 153));
        jLabel30.setOpaque(true);
        jDialog5.getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 900, 210));

        jLabel31.setBackground(new java.awt.Color(0, 204, 204));
        jLabel31.setOpaque(true);
        jDialog5.getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 900, 330));

        jLabel32.setBackground(new java.awt.Color(51, 255, 255));
        jLabel32.setOpaque(true);
        jDialog5.getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        jDialog6.setLocation(new java.awt.Point(0, 0));
        jDialog6.setMinimumSize(new java.awt.Dimension(290, 400));
        jDialog6.setResizable(false);
        jDialog6.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        try {
            jFormattedTextField6.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########?")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField6ActionPerformed(evt);
            }
        });
        jFormattedTextField5.setFont(new java.awt.Font("Segoe UI", 0, 18));
        jDialog6.getContentPane().add(jFormattedTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 180, 40));
        jFormattedTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18));

        jButton18.setBackground(new java.awt.Color(51, 153, 0));
        jButton18.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jButton18.setForeground(new java.awt.Color(0, 51, 0));
        jButton18.setText("Buscar");
        jButton18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jDialog6.getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 140, -1));

        jButton19.setBackground(new java.awt.Color(51, 153, 0));
        jButton19.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jButton19.setForeground(new java.awt.Color(0, 51, 0));
        jButton19.setText("Eliminar");
        jButton19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jDialog6.getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 140, -1));

        jButton20.setBackground(new java.awt.Color(51, 153, 0));
        jButton20.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jButton20.setForeground(new java.awt.Color(0, 51, 0));
        jButton20.setText("Modificar");
        jButton20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jDialog6.getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 140, -1));

        jLabel43.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(0, 102, 0));
        jLabel43.setText("DNI Usuario");
        jDialog6.getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel45.setBackground(new java.awt.Color(0, 102, 102));
        jLabel45.setOpaque(true);
        jDialog6.getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 750, 110));

        jLabel46.setBackground(new java.awt.Color(0, 153, 153));
        jLabel46.setOpaque(true);
        jDialog6.getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 750, 260));

        jLabel47.setBackground(new java.awt.Color(0, 204, 204));
        jLabel47.setOpaque(true);
        jDialog6.getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 750, 370));

        jLabel48.setBackground(new java.awt.Color(51, 255, 255));
        jLabel48.setOpaque(true);
        jDialog6.getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 420));

        jDialog7.setMinimumSize(new java.awt.Dimension(1140, 200));
        jDialog7.setPreferredSize(new java.awt.Dimension(1140, 200));

        jTable1.setBackground(new java.awt.Color(0, 204, 204));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(51, 153, 0));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        jDialog7.getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));
        setMaximumSize(new java.awt.Dimension(600, 400));
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 0));
        jButton1.setText("Administrador");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 153, 0));
        jButton2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 51, 0));
        jButton2.setText("Cliente");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setText("Gestion de Banca");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, 70));

        jLabel5.setBackground(new java.awt.Color(0, 51, 51));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 410));

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 140, 410));

        jLabel3.setBackground(new java.awt.Color(0, 153, 153));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 190, 410));

        jLabel2.setBackground(new java.awt.Color(0, 255, 255));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 400));

        jLabel7.setBackground(new java.awt.Color(51, 255, 255));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jDialog4.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jDialog3.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       
        JOptionPane.showMessageDialog(null, "Su saldo es de: "+consultarSaldo(usuario),"Consultar saldo",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Float ingreso = Float.valueOf(JOptionPane.showInputDialog(null,"Dinero a ingresar: ","Ingreso de dinero",JOptionPane.QUESTION_MESSAGE));
        IngresarDinero(usuario, ingreso);
        int respuesta = JOptionPane.showConfirmDialog(null, "Quieres ver saldo?", "Consulta de saldo",JOptionPane.YES_NO_OPTION);
        if (respuesta==0) {
              JOptionPane.showMessageDialog(null, "Su saldo es de: "+consultarSaldo(usuario),"Consultar saldo",JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         Float retiro = Float.valueOf(JOptionPane.showInputDialog(null,"Dinero a retirar: ","Retirada de dinero",JOptionPane.QUESTION_MESSAGE));
         if (consultarSaldo(usuario)<retiro) {
             JOptionPane.showMessageDialog(null, "Saldo insuficiente", "Saldo insuficiente",JOptionPane.ERROR_MESSAGE);  
        }else{
             RetirarDinero(usuario, retiro);
         }
         int respuesta = JOptionPane.showConfirmDialog(null, "Quieres ver saldo?", "Consulta de saldo",JOptionPane.YES_NO_OPTION);
        if (respuesta==0) {
              JOptionPane.showMessageDialog(null, "Su saldo es de: "+consultarSaldo(usuario),"Consultar saldo",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jButton18.setVisible(false);
        jButton19.setVisible(true);
        jButton20.setVisible(false);
        jDialog6.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jDialog5.setVisible(true);
        jTextField6.setVisible(true);
        jTextField11.setVisible(true);
        jLabel39.setVisible(true);
        jLabel41.setVisible(true);
        jButton21.setVisible(false);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        jButton18.setVisible(false);
        jButton19.setVisible(false);
        jButton20.setVisible(true);
        jDialog6.setVisible(true);
        jTextField6.setVisible(false);
        jTextField11.setVisible(false);
        jLabel39.setVisible(false);
        jLabel41.setVisible(false);
        jButton14.setVisible(false);
        jButton15.setVisible(false);
        jButton21.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        jButton18.setVisible(true);
        jButton19.setVisible(false);
        jButton20.setVisible(false);
        jDialog6.setVisible(true);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        
        if (jPasswordField1.getText().equals(Comprobar(jTextField2.getText()))) {
            jDialog1.setVisible(true);
            jDialog3.setVisible(false);
            usuario=jTextField2.getText();
        }else{
            JOptionPane.showMessageDialog(null, "Contraseña incorrectos","Contrasaeña incorrecta",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        if (jTextField3.getText().equalsIgnoreCase("admin")&&jPasswordField2.getText().equals("admin")) {
            jDialog2.setVisible(true);
            jDialog4.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "Usuario o Contraseña incorrectos","Contrasaeña incorrecta",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        Usuario user = new Usuario();
        user.setNombre(jTextField1.getText());
        user.setApellido(jTextField5.getText());
        user.setDni(jFormattedTextField5.getText());
        user.setDireccion(jTextField10.getText());
        user.setCiudad(jTextField4.getText());
        user.setTelefono(Integer.parseInt(jFormattedTextField2.getText()));
        user.setFechaNac(jFormattedTextField1.getText());
        user.setIBAN(jTextField6.getText());
        user.setContraseña(jTextField11.getText()); 
        AgregarCliente(user);
        JOptionPane.showMessageDialog(null, "Cliente: "+user.getNombre()+" ha sido dado de alta","Alta Cliente",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        BigInteger numero = new BigInteger(73, random);
        String iban = "ES"+numero.toString();
        while(ListaIbans().contains(iban)){
            numero = new BigInteger(73, random);
            iban = "ES"+numero.toString();
        }
        jTextField6.setText(iban);
        String CARACTERES = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789@_";
        StringBuilder sb = new StringBuilder(10);
        for (int i = 0; i < 10; i++) {
            int index = random.nextInt(CARACTERES.length());
            sb.append(CARACTERES.charAt(index));
        }
        jTextField11.setText(sb.toString());
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
             
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jFormattedTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jFormattedTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFormattedTextField1MouseClicked
        // TODO add your handling code h
    }//GEN-LAST:event_jFormattedTextField1MouseClicked

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        jDialog7.setVisible(true);
        buscarCliente(jFormattedTextField6.getText());
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jFormattedTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField6ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        jButton18.doClick();
        eliminar(jFormattedTextField6.getText());
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        Usuario use = obetenerDatos(jFormattedTextField6.getText());
        jDialog5.setVisible(true);
        jTextField1.setText(use.getNombre());
        jTextField5.setText(use.getApellido());
        jFormattedTextField5.setText(use.getDni());
        jTextField10.setText(use.getDireccion());
        jTextField4.setText(use.getCiudad());
        jFormattedTextField2.setText(String.valueOf(use.getTelefono()));
        jFormattedTextField1.setText(use.getFechaNac());
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        Usuario us = new Usuario();
        us.setNombre(jTextField1.getText());
        us.setApellido(jTextField5.getText());
        us.setDni(jFormattedTextField5.getText());
        us.setDireccion(jTextField10.getText());
        us.setCiudad(jTextField4.getText());
        us.setTelefono(Integer.parseInt(jFormattedTextField2.getText()));
        us.setFechaNac(jFormattedTextField1.getText());
        modificar(jFormattedTextField6.getText(), us);
    }//GEN-LAST:event_jButton21ActionPerformed
    
    public String Comprobar (String dni){
        String contra=null;
        try {
            String sql = "select contraseña from cliente where dni =?";
            PreparedStatement stmt = cone.estableceConnection().prepareStatement(sql);
            stmt.setString(1, dni);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                 contra = rs.getString("contraseña");
                 
            }else{
                JOptionPane.showMessageDialog(null, "Usuario incorrectos","Contrasaeña incorrecta",JOptionPane.ERROR_MESSAGE);
            }
           
        } catch (SQLException ex) {
            Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
        }
        return contra;
    }
    
    public Double consultarSaldo(String dni){
          Double saldo = null;
        try {
            String sql = "select cuenta.saldo from cuenta join cliente on cliente.iban = cuenta.iban where cliente.dni =? ";
            PreparedStatement stmt = cone.estableceConnection().prepareStatement(sql);
            stmt.setString(1, dni);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                 saldo = rs.getDouble("saldo");
                 
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       return saldo;
        
    }
    
    public void IngresarDinero(String dni, Float ingreso){
        try {
            String sql = "Update cuenta set saldo = saldo + ? where IBAN like (select IBAN from cliente where dni like ?)";
            PreparedStatement stmt = cone.estableceConnection().prepareStatement(sql);
            stmt.setFloat(1, ingreso);
            stmt.setString(2, dni);
            stmt.execute();
            
        } catch (SQLException ex) {
            Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    public void RetirarDinero(String dni, Float ingreso){
        try {
            String sql = "Update cuenta set saldo = saldo - ? where IBAN like (select IBAN from cliente where dni like ?)";
            PreparedStatement stmt = cone.estableceConnection().prepareStatement(sql);
            stmt.setFloat(1, ingreso);
            stmt.setString(2, dni);
            stmt.execute();
            
        } catch (SQLException ex) {
            Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void AgregarCliente (Usuario user){
        try {
            String sql = "INSERT INTO cliente (DNI, nombre, apellidos, direccion, ciudad, fechaNac, telefono, contraseña, IBAN) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement stmt = cone.estableceConnection().prepareStatement(sql);
            stmt.setString(1, user.getDni());
            stmt.setString(2, user.getNombre());
            stmt.setString(3, user.getApellido());
            stmt.setString(4, user.getDireccion());
            stmt.setString(5, user.getCiudad());
            stmt.setDate(6, Date.valueOf(user.getFechaNac()));
            stmt.setInt(7, user.getTelefono());
            stmt.setString(8, user.getContraseña());
            stmt.setString(9, user.getIBAN());
            stmt.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    
    public ArrayList ListaIbans(){
        ArrayList<String> ListaIban = new ArrayList<>();
        try {
            
            String sql = "select iban from cuenta";
            PreparedStatement stmt = cone.estableceConnection().prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            
            while(rs.next()){
                ListaIban.add(rs.getString("IBAN"));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
        }
        return ListaIban;               
    }
    
    public void ComprobarCaracteresDNI(String DNI){
        boolean comp = false;
        char[] splitDNi = new char[9];
        ArrayList<Character> caracteres = new ArrayList<>(Arrays.asList('1', '2', '3', '4', '5', '6', '7', '8', '9', '0')
        );
        for (int i = 0; i < 9; i++) {
            splitDNi[i]=DNI.charAt(i);
        }
        for (int i = 0; i < 8; i++) {
            if (!caracteres.contains(splitDNi[i])) {
                comp=true;
            }
        }
    }
    public void buscarCliente(String DNI){
        DefaultTableModel modelo =(DefaultTableModel) jTable1.getModel();
        modelo.setColumnCount(0);
        modelo.setRowCount(0);
        jTable1.setModel(modelo);
        
        modelo.addColumn("DNI");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Direccion");
        modelo.addColumn("Ciudad");
        modelo.addColumn("Fecha de Nacimiento");
        modelo.addColumn("Telefono");
        modelo.addColumn("IBAN");
        
        String sql = "select DNI, nombre, apellidos, direccion, ciudad, fechaNac, telefono,IBAN from cliente where DNI like ?";
        PreparedStatement stmt;
        try {
            stmt = cone.estableceConnection().prepareStatement(sql);
            stmt.setString(1, DNI);
            ResultSet rs = stmt.executeQuery();
            while (rs.next()){
                modelo.addRow(new Object[]{
                    rs.getString("DNI"),
                    rs.getString("nombre"),
                    rs.getString("apellidos"),
                    rs.getString("direccion"),
                    rs.getString("ciudad"),
                    rs.getDate("fechaNac"),
                    rs.getInt("telefono"),
                    rs.getString("IBAN")
                });
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
        }
    } 
    
    public void eliminar(String DNI) {
    try {
        int respuesta = JOptionPane.showConfirmDialog(null, 
            "¿Seguro que quieres eliminar este usuario?", 
            "Confirmación", 
            JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            String sql = "DELETE FROM cliente WHERE DNI = ?";
            PreparedStatement stmt = cone.estableceConnection().prepareStatement(sql);
            stmt.setString(1, DNI);
            
            int filasAfectadas = stmt.executeUpdate();
            
            if (filasAfectadas > 0) {
                JOptionPane.showMessageDialog(null, 
                    "Usuario eliminado correctamente", 
                    "Usuario eliminado", 
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, 
                    "Usuario no encontrado o no se pudo eliminar", 
                    "Error", 
                    JOptionPane.ERROR_MESSAGE);
            }
        }

    } catch (SQLException ex) {
        Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, 
            "Error al intentar eliminar el usuario", 
            "Error SQL", 
            JOptionPane.ERROR_MESSAGE);
    }
}

    public Usuario obetenerDatos(String DNI){
        Usuario us = new Usuario();
        try {
            String sql = "select DNI, nombre, apellidos, direccion, ciudad, fechaNac,telefono from cliente where DNI like ?";
            PreparedStatement pstmt = cone.estableceConnection().prepareCall(sql);
            pstmt.setString(1, DNI);
            ResultSet rs = pstmt.executeQuery();
            
            while (rs.next()) {
                us.setNombre(rs.getString("nombre"));
                us.setDni(rs.getString("DNI"));
                us.setApellido(rs.getString("apellidos"));
                us.setDireccion(rs.getString("direccion"));
                us.setCiudad(rs.getString("ciudad"));
                us.setFechaNac(String.valueOf(rs.getDate("fechaNac")));
                us.setTelefono(rs.getInt("telefono"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
        }
        return us;
    }
    
    public void modificar(String DNI , Usuario user){
        try {
            String sql = "Update cliente set DNI = ? ,Nombre = ?, Apellidos = ?, Direccion = ?, Ciudad = ?, Telefono = ?, FechaNac = ? where DNI = ?";
            PreparedStatement stmt = cone.estableceConnection().prepareCall(sql);
            stmt.setString(1, user.getDni());
            stmt.setString(2, user.getNombre());
            stmt.setString(3, user.getApellido());
            stmt.setString(4, user.getDireccion());
            stmt.setString(5, user.getCiudad());
            stmt.setInt(6, user.getTelefono());
            stmt.setDate(7, Date.valueOf(user.getFechaNac()));
            stmt.setString(8, DNI);
            stmt.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Pantalla.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JDialog jDialog5;
    private javax.swing.JDialog jDialog6;
    private javax.swing.JDialog jDialog7;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
